version: "3.4"

services:

  django:
    build:
      context: .
      dockerfile: ./Dockerfile.be
    ports:
      - 8000:8000
    volumes:
      - ./biddingly-be:/code
    depends_on:
      frontend:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.fe
    volumes:
      - "./biddingly-fe:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    depends_on:
      firefox:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      timeout: 20s
      retries: 10


  selenium-hub:
    image: selenium/hub:4.8.0-20230123
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
  
  firefox:
    image: selenium/node-firefox:4.8.0-20230123
    shm_size: 2gb
    ports:
      - 7900:7900
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    healthcheck:
      test: curl --fail http://localhost:7900 || exit 1
      timeout: 20s
      retries: 10
