version: "3.4"

services:

  django:
    build: ./biddingly-be
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - "./biddingly-be:/code"

  frontend:
    build: ./biddingly-fe
    volumes:
      - "./biddingly-fe:/app"
    ports:
      - "3000:3000"

  selenium-hub:
    image: selenium/hub:4.8.0-20230123
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  firefox:
    image: selenium/node-firefox:4.8.0-20230123
    shm_size: 2gb
    ports:
      - "7900:7900"
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
